scarsdale-assessor-2012.txt:
	pdftotext scarsdale-assessor-2012.pdf
scarsdale-assessor-2012-layout.txt:
	pdftotext -layout scarsdale-assessor-2012.pdf scarsdale-assessor-2012-layout.txt
scarsdale-assessor-2012.html:
	pdftohtml scarsdale-assessor-2012.pdf
scarsdale-assessor-2012.xml:
	pdftohtml -xml scarsdale-assessor-2012.pdf
scarsdale-assessor-2012-page1.svg:
	inkscape --without-gui --export-plain-svg scarsdale-assessor-2012-page1.svg scarsdale-assessor-2012.pdf
